-- Inserir Módulo 4 - Risco e Retorno
INSERT INTO public.lessons (id, section_id, section_title, lesson_number, title, xp_reward, is_quiz, activity_data) VALUES
(gen_random_uuid(), 4, 'Risco e Retorno', 1, '4.1 O que é Risco?', 25, false, '[
  {"type": "explanation", "title": "Risco não é vilão — é variável 🎲", "body": "No mercado financeiro, risco é a possibilidade de o resultado real ser diferente do esperado — pra cima ou pra baixo. Não significa necessariamente perda. Significa incerteza. Todo investimento tem algum nível de risco. Quem diz que tem investimento sem risco, está mentindo ou escondendo algo.", "emoji": "💡"},
  {"type": "example", "title": "O Risco do Guarda-Chuva 🌂", "body": "Você sai de casa sem guarda-chuva. Pode chover ou não. Isso é risco — incerteza sobre o resultado. No mercado, você compra uma ação. Pode valorizar ou desvalorizar. A diferença é que no mercado você pode estudar os dados, a história e os fundamentos pra tomar uma decisão mais informada. Risco não some — mas pode ser entendido e gerenciado.", "highlight": "Risco = possibilidade de resultado diferente do esperado\nNão é sinônimo de perda — é sinônimo de incerteza\nTodo investimento tem risco — inclusive a poupança\nRisco pode ser medido, analisado e gerenciado\nMaior risco → maior potencial de retorno", "emoji": "🎯"},
  {"type": "activity", "question": "No contexto de investimentos, o que melhor define o conceito de risco?", "options": ["A certeza de perder dinheiro em um investimento", "A possibilidade de o resultado ser diferente do esperado", "A taxa de juros cobrada pelo banco", "O valor mínimo necessário para investir"], "correct": 1},
  {"type": "true_false", "statement": "A poupança é um investimento completamente sem risco, pois é garantida pelo governo brasileiro.", "correct": 0, "explanation": "Falso! Mesmo a poupança possui risco — o de inflação superar o rendimento, fazendo o investidor perder poder de compra. Além disso, a garantia do FGC cobre apenas até R$ 250.000 por instituição."},
  {"type": "fill_in_the_blank", "sentence": "Em investimentos, a relação básica do mercado diz que quanto maior o risco, maior o potencial de ____.", "answer": "retorno", "hint": "É o que você ganha pelo dinheiro investido. 💰", "explanation": "Correto! Risco e retorno andam juntos — ninguém oferece alto retorno sem alto risco. Se parecer bom demais pra ser verdade, desconfie."},
  {"type": "match_pairs", "pairs": [{"term": "Risco", "definition": "Incerteza sobre o resultado de um investimento"}, {"term": "Volatilidade", "definition": "Medida da intensidade das oscilações de preço"}, {"term": "FGC", "definition": "Fundo Garantidor de Créditos — protege até R$250k"}, {"term": "Incerteza", "definition": "Impossibilidade de prever o resultado com certeza"}]}
]'),
(gen_random_uuid(), 4, 'Risco e Retorno', 2, '4.2 Tipos de Risco', 25, false, '[
  {"type": "explanation", "title": "Nem todo risco é igual 🔍", "body": "Existem diferentes tipos de risco no mercado financeiro — e cada um age de forma diferente na sua carteira. Conhecer os tipos é o primeiro passo pra se proteger deles. Os três principais são: risco de mercado, risco de liquidez e risco de crédito.", "emoji": "💡"},
  {"type": "example", "title": "Três Riscos no Dia a Dia 🗓️", "body": "Risco de mercado: você compra PETR4 e o preço cai por causa de uma crise no petróleo. Risco de liquidez: você investe num FII com baixo volume e quando quer vender, não encontra comprador no preço justo. Risco de crédito: você empresta dinheiro via CDB e o banco quebra antes de te pagar de volta. Cada risco tem sua origem e sua solução.", "highlight": "Risco de mercado → oscilação de preços por fatores externos\nRisco de liquidez → dificuldade de vender o ativo rapidamente\nRisco de crédito → calote do emissor do título\nRisco sistêmico → crise que afeta todo o mercado\nRisco específico → problema pontual de uma empresa", "emoji": "🎯"},
  {"type": "activity", "question": "Um investidor não consegue vender suas cotas de um FII pelo preço justo porque há poucos compradores. Qual tipo de risco ele está enfrentando?", "options": ["Risco de crédito", "Risco de mercado", "Risco de liquidez", "Risco cambial"], "correct": 2},
  {"type": "true_false", "statement": "O risco específico de uma empresa pode ser completamente eliminado por meio de diversificação da carteira.", "correct": 1, "explanation": "Verdadeiro! O risco específico (de uma única empresa) pode ser reduzido a quase zero com diversificação. Já o risco sistêmico, que afeta todo o mercado, não pode ser eliminado dessa forma."},
  {"type": "fill_in_the_blank", "sentence": "O risco que afeta todo o mercado ao mesmo tempo, como em uma crise global, é chamado de risco ____.", "answer": "sistêmico", "hint": "Vem de sistema — quando o sistema inteiro é afetado. 🌍", "explanation": "Exato! O risco sistêmico impacta todos os ativos simultaneamente — como na crise de 2008 ou na pandemia de 2020. Não tem como eliminar, apenas atravessar."},
  {"type": "match_pairs", "pairs": [{"term": "Risco de mercado", "definition": "Oscilação de preços por fatores externos"}, {"term": "Risco de liquidez", "definition": "Dificuldade de converter o ativo em dinheiro"}, {"term": "Risco de crédito", "definition": "Possibilidade de calote do emissor"}, {"term": "Risco específico", "definition": "Risco exclusivo de uma empresa ou setor"}]}
]'),
(gen_random_uuid(), 4, 'Risco e Retorno', 3, '4.3 O que é Retorno?', 25, false, '[
  {"type": "explanation", "title": "O prêmio do investidor 🏆", "body": "Retorno é o ganho obtido com um investimento — pode vir de valorização do preço, de dividendos, de aluguéis ou de juros. Ele pode ser medido em reais ou em percentual. O que importa de verdade é o retorno real: o que ficou depois de descontar a inflação. Ganhar 10% quando a inflação foi 12% significa que você perdeu poder de compra.", "emoji": "💡"},
  {"type": "example", "title": "Retorno Nominal vs Retorno Real 🧮", "body": "Você investe R$ 1.000 e após 1 ano tem R$ 1.100. Retorno nominal: 10%. Mas a inflação no período foi 6%. Seu retorno real foi de aproximadamente 4% — o que de fato sobrou em poder de compra. É por isso que comparar investimentos com a inflação é tão importante quanto comparar com a Selic.", "highlight": "Retorno nominal → ganho bruto sem descontar inflação\nRetorno real → ganho após descontar inflação\nRetorno total → valorização + dividendos + aluguéis\nBenchmark → referência de comparação (ex: CDI, Ibovespa)\nSempre compare seu retorno com a inflação do período", "emoji": "🎯"},
  {"type": "activity", "question": "Se um investimento rendeu 8% no ano e a inflação foi de 5%, qual foi o retorno real aproximado?", "options": ["13%", "8%", "3%", "5%"], "correct": 2},
  {"type": "true_false", "statement": "Um investimento que rendeu 15% ao ano é sempre melhor do que um que rendeu 10%, independentemente da inflação do período.", "correct": 0, "explanation": "Falso! O que importa é o retorno real. Se o investimento de 15% ocorreu em um período com inflação de 14%, o retorno real foi de apenas ~1%. O contexto inflacionário é fundamental na análise."},
  {"type": "fill_in_the_blank", "sentence": "O retorno de um investimento descontado da inflação do período é chamado de retorno ____.", "answer": "real", "hint": "É o que sobra de verdade no seu poder de compra. 💡", "explanation": "Correto! Retorno real é o que realmente importa — é o ganho que ultrapassa a inflação e representa aumento genuíno de poder de compra."},
  {"type": "match_pairs", "pairs": [{"term": "Retorno nominal", "definition": "Ganho bruto sem descontar inflação"}, {"term": "Retorno real", "definition": "Ganho após desconto da inflação"}, {"term": "CDI", "definition": "Principal benchmark de renda fixa no Brasil"}, {"term": "Ibovespa", "definition": "Principal benchmark de renda variável no Brasil"}]}
]'),
(gen_random_uuid(), 4, 'Risco e Retorno', 4, '4.4 Risco x Retorno — A Relação Fundamental', 25, false, '[
  {"type": "explanation", "title": "A lei mais básica do mercado ⚖️", "body": "No mercado financeiro, risco e retorno são inseparáveis. Quanto maior o risco que você assume, maior é o retorno potencial que o mercado oferece como compensação. Não existe alto retorno sem alto risco — e qualquer promessa do contrário é golpe. Essa relação é a bússola de todo investidor inteligente.", "emoji": "💡"},
  {"type": "example", "title": "A Pirâmide do Risco 🏔️", "body": "Na base: poupança e Tesouro Selic — baixíssimo risco, retorno modesto. No meio: ações de grandes empresas e FIIs — risco moderado, retorno potencial melhor. No topo: small caps, opções e cripto — risco elevado, potencial de ganho muito alto. Cada investidor decide em qual andar da pirâmide quer estar — e pode estar em vários ao mesmo tempo.", "highlight": "Baixo risco → Tesouro Direto, poupança, CDB de banco grande\nRisco moderado → ações de blue chips, FIIs, ETFs\nAlto risco → small caps, cripto, opções, alavancagem\nRegra de ouro: nunca assuma risco maior do que pode suportar\nDiversificação → forma de equilibrar risco e retorno", "emoji": "🎯"},
  {"type": "activity", "question": "Por que investimentos de maior risco tendem a oferecer maior retorno potencial?", "options": ["Por determinação do governo federal", "Como compensação ao investidor pelo risco adicional assumido", "Porque têm menor liquidez que outros investimentos", "Por causa da inflação acumulada no período"], "correct": 1},
  {"type": "true_false", "statement": "É possível encontrar investimentos com altíssimo retorno garantido e risco zero — basta pesquisar bem.", "correct": 0, "explanation": "Falso! Promessa de alto retorno com risco zero é sinal claro de fraude ou pirâmide financeira. A relação entre risco e retorno é uma lei do mercado — não tem como burlar."},
  {"type": "fill_in_the_blank", "sentence": "Qualquer investimento que prometa alto retorno com risco zero deve ser tratado como sinal de possível ____.", "answer": "golpe", "hint": "Também chamado de fraude ou pirâmide financeira. 🚨", "explanation": "Isso! Alto retorno + risco zero = golpe. Sempre. A relação risco-retorno é inviolável no mercado financeiro legítimo."},
  {"type": "match_pairs", "pairs": [{"term": "Baixo risco", "definition": "Tesouro Selic, poupança — retorno modesto e previsível"}, {"term": "Risco moderado", "definition": "Ações de grandes empresas — retorno potencial maior"}, {"term": "Alto risco", "definition": "Cripto, opções — potencial elevado, perdas também"}, {"term": "Pirâmide financeira", "definition": "Fraude que promete alto retorno sem risco real"}]}
]'),
(gen_random_uuid(), 4, 'Risco e Retorno', 5, '4.5 Como o Tempo Reduz o Risco?', 25, false, '[
  {"type": "explanation", "title": "O tempo é o melhor amigo do investidor ⏳", "body": "Quanto mais tempo você permanece investido, menor é a chance de sair no prejuízo em renda variável. Isso acontece porque crises são temporárias — o mercado historicamente sempre se recuperou. Quem vendeu no pico da crise de 2020 realizou a perda. Quem segurou, recuperou tudo em poucos meses.", "emoji": "💡"},
  {"type": "example", "title": "O Ibovespa ao Longo do Tempo 📅", "body": "Em março de 2020, o Ibovespa despencou 45% com o início da pandemia. Parecia o fim. Quem segurou: em dezembro de 2020, o índice já havia recuperado tudo e atingido novas máximas. Quem vendeu no pânico: realizou perdas de 45% e não pegou a recuperação. O tempo transforma crises em ruídos na linha do longo prazo.", "highlight": "Curto prazo → alta volatilidade, risco elevado\nMédio prazo → oscilações menores, tendência mais clara\nLongo prazo → crises viram ruído, retorno histórico positivo\nIbovespa: retorno médio histórico de ~12-15% ao ano\nTempo no mercado > momento de entrar no mercado", "emoji": "🎯"},
  {"type": "activity", "question": "Por que investidores de longo prazo tendem a ter resultados melhores em renda variável?", "options": ["Porque pagam menos impostos que investidores de curto prazo", "Porque o tempo permite atravessar crises e capturar o crescimento histórico do mercado", "Porque têm acesso a ações exclusivas não disponíveis para outros", "Porque recebem taxa de administração menor das corretoras"], "correct": 1},
  {"type": "true_false", "statement": "Vender ações no momento de queda do mercado é sempre a decisão mais prudente para proteger o patrimônio.", "correct": 0, "explanation": "Falso! Vender na queda realiza a perda de forma definitiva. Historicamente, mercados se recuperam — quem manteve a posição em crises anteriores foi recompensado com a recuperação."},
  {"type": "fill_in_the_blank", "sentence": "A estratégia de manter ações por muitos anos sem vender nas oscilações é chamada de ____ and hold.", "answer": "buy", "hint": "Em inglês, significa comprar e segurar. 🤝", "explanation": "Isso! Buy and hold — comprar e manter — é uma das estratégias mais simples e eficientes no longo prazo, evitando decisões emocionais em momentos de volatilidade."},
  {"type": "match_pairs", "pairs": [{"term": "Buy and hold", "definition": "Estratégia de manter ações por longo prazo"}, {"term": "Curto prazo", "definition": "Horizonte com maior exposição à volatilidade"}, {"term": "Longo prazo", "definition": "Horizonte onde crises tendem a virar ruído"}, {"term": "Realizar perda", "definition": "Vender o ativo com preço abaixo do valor de compra"}]}
]'),
(gen_random_uuid(), 4, 'Risco e Retorno', 6, '4.6 O que é Volatilidade?', 25, false, '[
  {"type": "explanation", "title": "O termômetro do mercado 🌡️", "body": "Volatilidade mede o quanto o preço de um ativo oscila em determinado período. Um ativo muito volátil sobe e cai muito em pouco tempo. Um ativo pouco volátil se move de forma mais suave. Volatilidade não é boa nem ruim — é uma característica. Mas ela precisa estar alinhada com o perfil e o prazo do investidor.", "emoji": "💡"},
  {"type": "example", "title": "Bitcoin vs Tesouro Selic 🎢", "body": "O Bitcoin pode subir 20% numa semana e cair 30% na seguinte — volatilidade extrema. O Tesouro Selic sobe todos os dias de forma suave e previsível — volatilidade próxima de zero. No meio-termo, as ações de grandes empresas: oscilam, mas de forma mais controlada que cripto. Quanto mais volátil, mais o investidor precisa de estômago e horizonte longo.", "highlight": "Alta volatilidade → Bitcoin, small caps, opções\nVolatilidade moderada → ações de blue chips, FIIs\nBaixa volatilidade → Tesouro Selic, CDB\nDesvio padrão → medida estatística de volatilidade\nVolatilidade ≠ perda — é oscilação, pra cima e pra baixo", "emoji": "🎯"},
  {"type": "activity", "question": "Um ativo com alta volatilidade se caracteriza por:", "options": ["Preço estável e previsível ao longo do tempo", "Rendimento fixo garantido independente do mercado", "Oscilações intensas de preço em curtos períodos", "Baixo potencial de retorno no longo prazo"], "correct": 2},
  {"type": "true_false", "statement": "Um investimento com alta volatilidade é sempre um mau investimento e deve ser evitado por todos os perfis.", "correct": 0, "explanation": "Falso! Alta volatilidade pode ser aceitável — e até desejável — para investidores com perfil arrojado e longo horizonte de tempo. O que importa é o alinhamento com o perfil e os objetivos do investidor."},
  {"type": "fill_in_the_blank", "sentence": "A medida estatística usada para quantificar a volatilidade de um ativo é chamada de desvio ____.", "answer": "padrão", "hint": "É uma medida de dispersão em torno da média. 📊", "explanation": "Isso! O desvio padrão mede o quanto os retornos de um ativo se afastam da média — quanto maior, mais volátil e imprevisível é o ativo."},
  {"type": "match_pairs", "pairs": [{"term": "Alta volatilidade", "definition": "Oscilações intensas de preço — Bitcoin, small caps"}, {"term": "Baixa volatilidade", "definition": "Movimento suave e previsível — Tesouro Selic"}, {"term": "Desvio padrão", "definition": "Medida estatística de volatilidade"}, {"term": "Blue chip", "definition": "Ação de empresa grande com volatilidade moderada"}]}
]'),
(gen_random_uuid(), 4, 'Risco e Retorno', 7, '4.7 Exemplos de Ativos por Nível de Risco', 25, false, '[
  {"type": "explanation", "title": "Cada ativo no seu lugar na pirâmide 🏔️", "body": "Todos os ativos financeiros podem ser posicionados numa pirâmide de risco. Na base ficam os mais seguros e previsíveis. No topo, os mais arriscados e voláteis. Conhecer onde cada ativo se encaixa ajuda a montar uma carteira consciente — sem surpresas desagradáveis.", "emoji": "💡"},
  {"type": "example", "title": "A Pirâmide Completa 📊", "body": "Base (baixo risco): Tesouro Selic, CDB de banco grande, poupança. Meio inferior: Tesouro IPCA+, debêntures de empresas sólidas. Meio superior: FIIs, ETFs de índice, ações de blue chips. Topo inferior: small caps, BDRs de empresas em crescimento. Topo (alto risco): opções, day trade, cripto. Cada camada tem seu papel numa carteira equilibrada.", "highlight": "Baixo risco → Tesouro Selic, poupança, CDB\nMédio-baixo → Tesouro IPCA+, debentures\nMédio → FIIs, ETFs, blue chips\nMédio-alto → small caps, BDRs growth\nAlto → opções, cripto, day trade", "emoji": "🎯"},
  {"type": "activity", "question": "Qual dos seguintes ativos está posicionado na base da pirâmide de risco — ou seja, é o mais conservador?", "options": ["Criptomoedas", "Ações de small caps", "Tesouro Selic", "Opções de ações"], "correct": 2},
  {"type": "true_false", "statement": "FIIs e ETFs de índice são considerados ativos de alto risco, equivalentes a criptomoedas na pirâmide de investimentos.", "correct": 0, "explanation": "Falso! FIIs e ETFs de índice são considerados de risco moderado — muito abaixo de criptomoedas e opções. São adequados para perfis moderados com horizonte de médio e longo prazo."},
  {"type": "match_pairs", "pairs": [{"term": "Tesouro Selic", "definition": "Base da pirâmide — risco mínimo"}, {"term": "ETF de índice", "definition": "Meio da pirâmide — risco moderado"}, {"term": "Small caps", "definition": "Topo inferior — risco médio-alto"}, {"term": "Criptomoedas", "definition": "Topo da pirâmide — risco máximo"}]}
]'),
(gen_random_uuid(), 4, 'Risco e Retorno', 8, '4.8 Perda Máxima: Como Calcular?', 25, false, '[
  {"type": "explanation", "title": "Saber o pior cenário antes de entrar 🧮", "body": "Antes de fazer qualquer investimento, o investidor consciente se pergunta: qual é o pior que pode acontecer? Calcular a perda máxima possível — o chamado drawdown máximo — ajuda a tomar decisões com consciência e evitar aportes que você não conseguiria suportar emocionalmente numa queda.", "emoji": "💡"},
  {"type": "example", "title": "Calculando o Pior Cenário 📉", "body": "Você tem R$ 10.000 e quer investir tudo em uma ação. No histórico, essa ação já caiu 60% em uma crise. Perda máxima potencial: R$ 6.000. Você consegue dormir perdendo R$ 6.000 temporariamente? Se não, ou você investe menos, ou escolhe um ativo menos volátil. Nunca invista um valor cuja perda te tiraria o sono — ou te forçaria a vender no pior momento.", "highlight": "Drawdown = queda do pico até o fundo em determinado período\nPerda máxima = % ou R$ que você pode perder no pior caso\nRegra prática: invista só o que pode ficar imobilizado por anos\nNunca use dinheiro de emergência em renda variável\nPosition sizing → quanto alocar em cada ativo com consciência", "emoji": "🎯"},
  {"type": "activity", "question": "Se você investe R$ 5.000 em uma ação que historicamente já caiu 40%, qual é a perda máxima potencial?", "options": ["R$ 400", "R$ 4.000", "R$ 2.000", "R$ 500"], "correct": 2},
  {"type": "true_false", "statement": "É seguro investir o dinheiro da reserva de emergência em ações, pois o retorno potencial compensa o risco de precisar do valor.", "correct": 0, "explanation": "Falso! A reserva de emergência deve estar em ativos líquidos e seguros — como Tesouro Selic ou CDB com liquidez diária. Nunca em renda variável, pois você pode precisar do dinheiro num momento em que o mercado está em queda."},
  {"type": "fill_in_the_blank", "sentence": "A maior queda registrada de um ativo entre seu pico e seu fundo histórico é chamada de ____ máximo.", "answer": "drawdown", "hint": "Vem do inglês draw down — puxar para baixo. 📉", "explanation": "Correto! O drawdown máximo mostra o pior cenário histórico de perda — uma referência essencial antes de investir em qualquer ativo de renda variável."},
  {"type": "match_pairs", "pairs": [{"term": "Drawdown", "definition": "Queda do pico até o fundo em determinado período"}, {"term": "Reserva de emergência", "definition": "Capital que não deve estar em renda variável"}, {"term": "Position sizing", "definition": "Definir quanto alocar em cada ativo"}, {"term": "Perda máxima", "definition": "Pior resultado possível do investimento em reais ou %"}]}
]'),
(gen_random_uuid(), 4, 'Risco e Retorno', 9, '4.9 Diversificação como Proteção', 25, false, '[
  {"type": "explanation", "title": "Não coloque todos os ovos na mesma cesta 🥚", "body": "Diversificação é a estratégia de distribuir o capital entre diferentes ativos para reduzir o risco total da carteira. Quando um ativo cai, outro pode subir ou se manter — suavizando o impacto. É a única estratégia que reduz risco sem necessariamente reduzir retorno.", "emoji": "💡"},
  {"type": "example", "title": "A Carteira que Sobrevive a Tudo 🛡️", "body": "Imagine uma carteira com: 40% em ETFs de índice, 30% em FIIs para renda mensal, 20% em ações de setores diferentes (energia, tecnologia, consumo), 10% em BDRs para exposição internacional. Se uma ação específica cai 50%, ela representa apenas uma fração da carteira. O impacto total é muito menor. Isso é diversificação funcionando.", "highlight": "Diversificação por ativo → ações, FIIs, ETFs juntos\nDiversificação por setor → energia, tecnologia, saúde\nDiversificação geográfica → Brasil + EUA + outros\nDiversificação temporal → aportes regulares ao longo do tempo\nNão existe diversificação 100% — risco sistêmico sempre existe", "emoji": "🎯"},
  {"type": "activity", "question": "Qual tipo de risco a diversificação NÃO consegue eliminar completamente?", "options": ["Risco específico de uma empresa", "Risco de um setor específico entrar em crise", "Risco sistêmico — que afeta todo o mercado", "Risco de gestão de uma única empresa"], "correct": 2},
  {"type": "true_false", "statement": "Ter 50 ações diferentes do mesmo setor bancário representa uma carteira bem diversificada.", "correct": 0, "explanation": "Falso! Ter muitas ações do mesmo setor não é diversificação real. Se o setor bancário sofre uma crise, todas as 50 ações serão impactadas igualmente. Diversificação de verdade inclui setores, classes de ativos e geografias diferentes."},
  {"type": "fill_in_the_blank", "sentence": "A estratégia de fazer aportes regulares independente do preço do ativo, comprando mais quando está barato e menos quando está caro, é chamada de ____.", "answer": "DCA", "hint": "Vem do inglês Dollar Cost Averaging — custo médio em dólar. 📆", "explanation": "Correto! DCA (Dollar Cost Averaging) é uma forma de diversificação temporal — você investe todo mês um valor fixo, reduzindo o risco de entrar no pior momento."},
  {"type": "match_pairs", "pairs": [{"term": "Diversificação", "definition": "Distribuição do capital em diferentes ativos"}, {"term": "DCA", "definition": "Aportes regulares independentemente do preço"}, {"term": "Correlação", "definition": "Medida de como dois ativos se movem juntos"}, {"term": "Risco sistêmico", "definition": "Risco que a diversificação não consegue eliminar"}]}
]'),
(gen_random_uuid(), 4, 'Risco e Retorno', 10, '4.10 Quiz do Módulo 🎯', 25, true, '[
  {"type": "activity", "question": "Como melhor se define risco em investimentos?", "options": ["Certeza de perder dinheiro", "Possibilidade de resultado diferente do esperado", "Taxa de juros do período", "Custo da corretagem"], "correct": 1},
  {"type": "activity", "question": "Um investidor não consegue vender seu ativo rapidamente pelo preço justo. Qual risco é esse?", "options": ["Risco de crédito", "Risco de mercado", "Risco de liquidez", "Risco cambial"], "correct": 2},
  {"type": "activity", "question": "Se um investimento rendeu 12% e a inflação foi 8%, qual foi o retorno real aproximado?", "options": ["20%", "12%", "8%", "4%"], "correct": 3},
  {"type": "activity", "question": "Uma promessa de alto retorno garantido com risco zero é sinal de:", "options": ["Ótima oportunidade de investimento", "Produto exclusivo para grandes investidores", "Possível fraude ou pirâmide financeira", "Novo produto lançado pelo Tesouro Nacional"], "correct": 2},
  {"type": "activity", "question": "Qual estratégia histórica se mostrou eficiente para atravessar crises em renda variável?", "options": ["Vender tudo assim que o mercado cair", "Manter os investimentos com horizonte de longo prazo", "Migrar para cripto em momentos de queda", "Concentrar tudo em um único ativo seguro"], "correct": 1},
  {"type": "activity", "question": "O que é volatilidade de um ativo?", "options": ["A taxa de retorno garantida ao longo do tempo", "O custo de manutenção anual do investimento", "A intensidade das oscilações de preço em determinado período", "O prazo mínimo para resgatar o investimento"], "correct": 2},
  {"type": "activity", "question": "Qual ativo está posicionado na BASE da pirâmide de risco?", "options": ["Criptomoedas", "Small caps", "Tesouro Selic", "Opções de ações"], "correct": 2},
  {"type": "activity", "question": "O que é drawdown máximo?", "options": ["O maior rendimento histórico de um ativo", "A maior queda registrada entre o pico e o fundo", "O valor mínimo para investir no ativo", "A taxa anual cobrada pelo gestor do fundo"], "correct": 1},
  {"type": "activity", "question": "Qual tipo de risco a diversificação NÃO consegue eliminar?", "options": ["Risco específico de uma empresa", "Risco de um setor isolado", "Risco sistêmico — crise global", "Risco de gestão da empresa"], "correct": 2},
  {"type": "activity", "question": "O que é DCA (Dollar Cost Averaging)?", "options": ["Estratégia de vender aos poucos em alta", "Aportes regulares independente do preço do ativo", "Cálculo do retorno real descontando inflação", "Taxa cambial do dólar aplicada em BDRs"], "correct": 1}
]'),
(gen_random_uuid(), 4, 'Risco e Retorno', 11, '4.11 Desafio: Classifique 5 Ativos por Nível de Risco', 25, false, '[
  {"type": "explanation", "title": "Hora de montar sua pirâmide 🏔️", "body": "Você aprendeu sobre risco, retorno, volatilidade e diversificação. Agora vamos praticar. A missão é pegar 5 ativos reais e classificá-los da pirâmide — do mais seguro ao mais arriscado. Não existe resposta 100% rígida — o contexto importa. Mas há uma lógica clara que você já conhece.", "emoji": "🎮"},
  {"type": "example", "title": "Os 5 Ativos do Desafio 🎯", "body": "Classifique do MENOS arriscado para o MAIS arriscado: Tesouro Selic, BOVA11 (ETF Ibovespa), VALE3 (ação da Vale), Bitcoin, MXRF11 (FII). Gabarito sugerido: 1º Tesouro Selic → 2º MXRF11 → 3º BOVA11 → 4º VALE3 → 5º Bitcoin. Você chegou perto? O raciocínio importa mais que a ordem exata.", "highlight": "1º (menor risco) → Tesouro Selic\n2º → MXRF11 (FII de papel)\n3º → BOVA11 (ETF diversificado)\n4º → VALE3 (ação individual, commodity)\n5º (maior risco) → Bitcoin", "emoji": "🎯"},
  {"type": "activity", "question": "Dos ativos abaixo, qual possui o MAIOR nível de risco e volatilidade?", "options": ["Tesouro Selic", "BOVA11 (ETF do Ibovespa)", "MXRF11 (FII)", "Bitcoin"], "correct": 3},
  {"type": "true_false", "statement": "Um ETF de índice como o BOVA11 é mais arriscado do que uma ação individual como VALE3, pois contém mais ativos.", "correct": 0, "explanation": "Falso! O BOVA11 é menos arriscado que VALE3 justamente por conter dezenas de ações. A diversificação reduz o risco específico — uma queda isolada da Vale impacta pouco o ETF, mas impacta diretamente quem só tem VALE3."},
  {"type": "match_pairs", "pairs": [{"term": "Tesouro Selic", "definition": "Menor risco — ideal para reserva de emergência"}, {"term": "BOVA11", "definition": "Risco moderado — diversificação automática"}, {"term": "VALE3", "definition": "Risco médio-alto — empresa individual de commodity"}, {"term": "Bitcoin", "definition": "Maior risco — volatilidade extrema"}]}
]')
ON CONFLICT DO NOTHING;

SELECT 'Módulo 4 inserido com sucesso!' as resultado;