-- Inserir Módulo 3 - Tipos de Investimentos
INSERT INTO public.lessons (id, section_id, section_title, lesson_number, title, xp_reward, is_quiz, activity_data) VALUES
(gen_random_uuid(), 3, 'Tipos de Investimentos', 1, '3.1 Ações', 25, false, '[
  {"type": "explanation", "title": "O clássico do mercado 📈", "body": "Você já conhece as ações do módulo anterior — mas agora elas entram como o primeiro tipo de investimento em renda variável. Comprar ação é a forma mais direta de ser sócio de uma empresa. Quando ela cresce, você cresce junto. Quando ela tropeça, seu bolso sente. É a essência da renda variável.", "emoji": "💡"},
  {"type": "example", "title": "O Sócio Invisível da Ambev 🍺", "body": "Cada vez que alguém compra uma Brahma no bar, a Ambev lucra. Se você tem ABEV3 na carteira, você participa desse lucro — sem trabalhar um dia sequer na fábrica. Ações permitem isso: ser sócio de negócios gigantes com poucos reais. A desvantagem? O preço oscila todo dia e não há garantia de retorno.", "highlight": "Vantagem: potencial de valorização alto no longo prazo\nVantagem: recebimento de dividendos\nDesvantagem: preço oscila diariamente\nDesvantagem: sem garantia de retorno\nIdeal para: quem tem horizonte de longo prazo", "emoji": "🎯"},
  {"type": "activity", "question": "Qual é a principal característica que diferencia ações de investimentos de renda fixa?", "options": ["Ações pagam juros mensais garantidos", "Ações têm rentabilidade variável e sem garantia", "Ações são emitidas pelo governo federal", "Ações não podem ser vendidas antes do vencimento"], "correct": 1},
  {"type": "true_false", "statement": "Investir em ações garante ao investidor um rendimento fixo e previsível todo mês.", "correct": 0, "explanation": "Falso! Ações são renda variável — o retorno depende do desempenho da empresa e do mercado. Não há rendimento fixo nem garantido."},
  {"type": "fill_in_the_blank", "sentence": "Ações são o tipo mais direto de investimento em renda variável pois transformam o comprador em ____ da empresa.", "answer": "sócio", "hint": "É quem divide os lucros e os riscos de um negócio. 🤝", "explanation": "Isso! Ao comprar uma ação você vira sócio — participa dos lucros, da valorização e também dos riscos."},
  {"type": "match_pairs", "pairs": [{"term": "Ação", "definition": "Fração do capital de uma empresa"}, {"term": "Dividendo", "definition": "Parte do lucro distribuída ao acionista"}, {"term": "Volatilidade", "definition": "Intensidade das oscilações de preço"}, {"term": "Longo prazo", "definition": "Horizonte ideal para investimento em ações"}]}
]'),
(gen_random_uuid(), 3, 'Tipos de Investimentos', 2, '3.2 FIIs — Fundos Imobiliários', 25, false, '[
  {"type": "explanation", "title": "Ser dono de imóvel sem ter imóvel 🏢", "body": "FII — Fundo de Investimento Imobiliário — é um jeito de investir no mercado imobiliário sem precisar comprar um apartamento ou sala comercial. Você compra cotas de um fundo que possui vários imóveis, e recebe uma fatia dos aluguéis todo mês. É como ter vários inquilinos pagando aluguel pra você — com R$ 100.", "emoji": "💡"},
  {"type": "example", "title": "O Dono do Shopping por R$ 100 🛍️", "body": "O FII XPML11, por exemplo, possui participação em vários shoppings do Brasil. Quando você compra uma cota desse fundo, você se torna indiretamente dono de uma fração desses shoppings. Todo mês, os aluguéis pagos pelas lojas são distribuídos proporcionalmente entre os cotistas — direto na sua conta. Sem reforma, sem IPTU, sem dor de cabeça de inquilino.", "highlight": "Rendimento mensal via distribuição de aluguéis\nIsento de IR nos rendimentos para pessoa física\nNegociado na bolsa como uma ação normal\nTicker termina em 11 (ex: MXRF11, HGLG11)\nNão precisa de muito dinheiro pra começar", "emoji": "🎯"},
  {"type": "activity", "question": "Como os FIIs distribuem rendimentos aos seus cotistas?", "options": ["Via valorização das cotas apenas, sem pagamentos mensais", "Por meio de juros fixos definidos no contrato", "Distribuindo os aluguéis recebidos pelos imóveis do fundo", "Pelo pagamento de dividendos trimestrais das empresas"], "correct": 2},
  {"type": "true_false", "statement": "Para investir em FIIs é necessário ter muito dinheiro, pois cada cota equivale ao valor de um imóvel completo.", "correct": 0, "explanation": "Falso! As cotas de FIIs são negociadas na bolsa por valores acessíveis — muitas custam entre R$ 10 e R$ 150, permitindo que qualquer pessoa invista no mercado imobiliário."},
  {"type": "fill_in_the_blank", "sentence": "Os tickers de Fundos Imobiliários sempre terminam com o número ____.", "answer": "11", "hint": "É o mesmo sufixo do ETF BOVA11. 🏷️", "explanation": "Correto! Sufixo 11 identifica ETFs e FIIs na bolsa brasileira — como MXRF11, HGLG11, XPML11."},
  {"type": "match_pairs", "pairs": [{"term": "FII", "definition": "Fundo que investe em imóveis e distribui aluguéis"}, {"term": "Cota", "definition": "Menor fração de um fundo de investimento"}, {"term": "IFIX", "definition": "Índice que acompanha o desempenho dos FIIs"}, {"term": "Rendimento mensal", "definition": "Distribuição proporcional dos aluguéis do fundo"}]}
]'),
(gen_random_uuid(), 3, 'Tipos de Investimentos', 3, '3.3 ETFs — Fundos de Índice', 25, false, '[
  {"type": "explanation", "title": "A cesta que compra tudo de uma vez 🧺", "body": "ETF — Exchange Traded Fund — é um fundo negociado na bolsa que replica um índice. Em vez de comprar ação por ação, você compra um único ETF e já fica exposto a dezenas ou centenas de empresas de uma vez. É o investimento preguiçoso no bom sentido — diversificação automática com uma única compra.", "emoji": "💡"},
  {"type": "example", "title": "BOVA11 — O Ibovespa na sua Conta 📊", "body": "O BOVA11 replica o Ibovespa — o principal índice da bolsa brasileira. Quando você compra uma cota do BOVA11, está investindo automaticamente nas maiores empresas do Brasil: Petrobras, Vale, Itaú, Ambev e mais 80 outras. Se o Ibovespa sobe 10%, seu BOVA11 sobe ~10%. Se cai, cai junto. Simples, barato e eficiente.", "highlight": "Diversificação automática com uma única compra\nTaxa de administração muito baixa (0,1% a 0,5% ao ano)\nNegociado na bolsa como uma ação normal\nIdeal pra quem quer simplicidade\nExemplos: BOVA11, IVVB11, SMAL11", "emoji": "🎯"},
  {"type": "activity", "question": "O que acontece com o valor de um ETF que replica o Ibovespa quando o índice sobe 5%?", "options": ["Permanece estável pois ETFs têm preço fixo", "Sobe aproximadamente 5%, replicando o índice", "Sobe mais de 5% pois ETFs têm alavancagem", "Cai pois ETFs funcionam inversamente ao índice"], "correct": 1},
  {"type": "true_false", "statement": "Um ETF como o BOVA11 exige que o investidor gerencie manualmente quais ações comprar e vender dentro do fundo.", "correct": 0, "explanation": "Falso! O ETF é gerenciado automaticamente para replicar o índice de referência. O investidor não precisa tomar nenhuma decisão sobre as ações individuais dentro do fundo."},
  {"type": "fill_in_the_blank", "sentence": "O ETF IVVB11 replica o índice americano ____, expondo o investidor brasileiro às 500 maiores empresas dos EUA.", "answer": "S&P 500", "hint": "É o índice mais famoso do mundo, criado em 1957. 🇺🇸", "explanation": "Exato! O IVVB11 replica o S&P 500 — uma forma simples de investir em Apple, Google, Amazon e outras gigantes americanas direto pela B3."},
  {"type": "match_pairs", "pairs": [{"term": "ETF", "definition": "Fundo negociado em bolsa que replica um índice"}, {"term": "BOVA11", "definition": "ETF que replica o Ibovespa"}, {"term": "IVVB11", "definition": "ETF que replica o S&P 500"}, {"term": "Taxa de administração", "definition": "Custo anual cobrado pelo gestor do fundo"}]}
]'),
(gen_random_uuid(), 3, 'Tipos de Investimentos', 4, '3.4 BDRs — Ações Gringas pelo Brasil', 25, false, '[
  {"type": "explanation", "title": "Apple e Google na sua corretora brasileira 🌎", "body": "BDR — Brazilian Depositary Receipt — é um certificado negociado na B3 que representa ações de empresas estrangeiras. Quer ser sócio da Apple, da Tesla ou da Disney sem abrir conta em corretora americana? BDR é a resposta. Você compra aqui, em reais, e fica exposto ao desempenho da empresa lá fora.", "emoji": "💡"},
  {"type": "example", "title": "AAPL34 — Apple no seu Home Broker 🍎", "body": "O BDR AAPL34 representa ações da Apple negociadas na B3. Cada BDR equivale a uma fração da ação original lá na NASDAQ. Se a Apple sobe 10% em Nova York, seu AAPL34 aqui no Brasil sobe aproximadamente 10% — ajustado pelo câmbio. Isso significa que o dólar também influencia: se o real desvaloriza, seus BDRs ficam mais valiosos em reais.", "highlight": "Ticker termina em 34 (ex: AAPL34, GOGL34, TSLA34)\nExposição ao dólar — proteção natural contra desvalorização do real\nNão precisa de conta em corretora americana\nLiquidez menor que as ações originais nos EUA\nIdeal para diversificação internacional simples", "emoji": "🎯"},
  {"type": "activity", "question": "Qual é a principal vantagem de investir em BDRs em vez de comprar ações diretamente em bolsas americanas?", "options": ["BDRs têm rentabilidade maior que as ações originais", "BDRs são isentos de imposto de renda", "É possível investir em empresas estrangeiras sem abrir conta fora do Brasil", "BDRs eliminam o risco cambial completamente"], "correct": 2},
  {"type": "true_false", "statement": "Investir em BDRs elimina completamente o risco cambial, pois as operações são realizadas em reais na B3.", "correct": 0, "explanation": "Falso! Mesmo sendo negociado em reais, o BDR é atrelado a uma ação estrangeira — então a variação do câmbio dólar/real impacta diretamente o valor do investimento."},
  {"type": "fill_in_the_blank", "sentence": "O sufixo ____ no ticker identifica um BDR negociado na B3, como em AAPL34 ou GOGL34.", "answer": "34", "hint": "É o mesmo número que aparece no final de MSFT34 e AMZO34. 🔢", "explanation": "Correto! O sufixo 34 é o padrão brasileiro para BDRs de nível 3 — os mais acessíveis ao investidor pessoa física."},
  {"type": "match_pairs", "pairs": [{"term": "BDR", "definition": "Certificado que representa ação estrangeira na B3"}, {"term": "AAPL34", "definition": "BDR da Apple negociado na B3"}, {"term": "Risco cambial", "definition": "Impacto da variação do dólar no investimento"}, {"term": "Sufixo 34", "definition": "Identifica BDRs no ticker brasileiro"}]}
]'),
(gen_random_uuid(), 3, 'Tipos de Investimentos', 5, '3.5 Opções — Uma Prévia', 25, false, '[
  {"type": "explanation", "title": "O contrato do futuro 📜", "body": "Opções são contratos que dão ao comprador o direito — mas não a obrigação — de comprar ou vender um ativo por um preço combinado até uma data determinada. É um assunto complexo que aparece com profundidade no Nível 3. Por agora, o importante é saber que existem e que são ferramentas poderosas — e perigosas — se usadas sem conhecimento.", "emoji": "💡"},
  {"type": "example", "title": "O Ingresso que Pode Não Ser Usado 🎟️", "body": "Imagina que você paga R$ 50 por um ingresso antecipado de um show que pode ser incrível ou um fracasso. Se o show for ótimo, você usa o ingresso e economiza porque ele estava mais barato. Se for péssimo, você não vai — mas perdeu os R$ 50. Com opções é parecido: você paga um valor (prêmio) pelo direito de comprar uma ação no futuro por um preço combinado hoje.", "highlight": "Opção de Compra (Call) → direito de comprar o ativo\nOpção de Venda (Put) → direito de vender o ativo\nPrêmio → valor pago pelo contrato da opção\nVencimento → data limite para exercer o direito\n⚠️ Risco elevado — aprofundamos no Nível 3", "emoji": "🎯"},
  {"type": "activity", "question": "O que é uma opção de compra (Call) no mercado financeiro?", "options": ["Uma obrigação de comprar um ativo por preço fixo", "Um direito de comprar um ativo por preço combinado até uma data", "Um empréstimo de ações entre investidores", "Um contrato de aluguel de ações"], "correct": 1},
  {"type": "true_false", "statement": "O comprador de uma opção é obrigado a exercer seu direito no vencimento, mesmo que o negócio não seja favorável.", "correct": 0, "explanation": "Falso! A opção dá um direito, não uma obrigação. Se não for vantajoso exercer, o comprador simplesmente não o faz — perdendo apenas o prêmio pago."},
  {"type": "match_pairs", "pairs": [{"term": "Call", "definition": "Opção de compra de um ativo"}, {"term": "Put", "definition": "Opção de venda de um ativo"}, {"term": "Prêmio", "definition": "Valor pago pelo contrato da opção"}, {"term": "Vencimento", "definition": "Data limite para exercer o direito da opção"}]}
]'),
(gen_random_uuid(), 3, 'Tipos de Investimentos', 6, '3.6 Criptomoedas como Renda Variável', 25, false, '[
  {"type": "explanation", "title": "O ativo mais volátil do pedaço 🎢", "body": "Criptomoedas como Bitcoin e Ethereum são ativos de renda variável — mas com uma volatilidade muito acima das ações tradicionais. Podem subir 300% em um ano e cair 70% no seguinte. Não são reguladas pela CVM nem pelo Banco Central, e não têm lastro em empresas reais. São um capítulo à parte no mundo dos investimentos.", "emoji": "💡"},
  {"type": "example", "title": "Bitcoin: de R$ 300 a R$ 600.000 🪙", "body": "Em 2013, 1 Bitcoin valia cerca de R$ 300. Em 2021, chegou perto de R$ 350.000. Em 2022, caiu para R$ 90.000. Em 2024, bateu novos recordes. Quem comprou cedo e segurou ficou rico — mas quem comprou no pico de 2021 esperou anos pra se recuperar. Cripto é renda variável no grau máximo: alta recompensa, altíssimo risco.", "highlight": "Volatilidade extrema — muito maior que ações\nSem regulação da CVM no Brasil\nOpera 24h por dia, 7 dias por semana\nNão tem lastro em empresa ou governo\nPerfil: apenas para quem aceita risco elevado", "emoji": "🎯"},
  {"type": "activity", "question": "Qual é a principal diferença entre investir em criptomoedas e Investing em ações de empresas?", "options": ["Criptomoedas têm rendimento fixo garantido", "Ações são mais voláteis que criptomoedas", "Criptomoedas não têm lastro em empresas reais e têm volatilidade muito maior", "Criptomoedas são reguladas pelo Banco Central"], "correct": 2},
  {"type": "true_false", "statement": "As criptomoedas são reguladas pela CVM e pelo Banco Central, oferecendo as mesmas proteções legais que ações e FIIs.", "correct": 0, "explanation": "Falso! Criptomoedas operam em um ambiente com regulação muito mais incipiente. No Brasil, a regulação de criptoativos ainda está em desenvolvimento, sem as mesmas proteções da CVM aplicadas a ações."},
  {"type": "fill_in_the_blank", "sentence": "Ao contrário das ações, o mercado de criptomoedas funciona ____ horas por dia, todos os dias da semana.", "answer": "24", "hint": "Não tem horário de pregão — funciona inclusive aos fins de semana. 🌐", "explanation": "Exato! Cripto não tem pregão — opera continuamente, 24h por dia, 7 dias por semana, em todo o mundo."},
  {"type": "match_pairs", "pairs": [{"term": "Bitcoin", "definition": "Primeira e mais famosa criptomoeda do mundo"}, {"term": "Volatilidade", "definition": "Característica marcante das criptomoedas — oscilações extremas"}, {"term": "Blockchain", "definition": "Tecnologia descentralizada que registra transações cripto"}, {"term": "Sem lastro", "definition": "Não representa participação em empresa ou pemerintah"}]}
]'),
(gen_random_uuid(), 3, 'Tipos de Investimentos', 7, '3.7 Comparando os Tipos', 25, false, '[
  {"type": "explanation", "title": "Cada ativo tem seu papel 🧩", "body": "Não existe o melhor tipo de investimento em renda variável — existe o mais adequado para cada objetivo, perfil e momento de vida. Ações, FIIs, ETFs, BDRs, opções e criptomoedas têm características muito diferentes. Entender cada um é o que permite montar uma carteira inteligente.", "emoji": "💡"},
  {"type": "example", "title": "A Carteira dos Sonhos 🎯", "body": "Um investidor equilibrado pode ter: ETFs para diversificação automática e baixo custo, FIIs para renda mensal via aluguéis, ações de empresas sólidas para crescimento de longo prazo, BDRs para exposição internacional, e uma pequena fatia em cripto para quem aceita o risco. Cada peça tem uma função — como um time bem escalado.", "highlight": "Ações → crescimento e dividendos no longo prazo\nFIIs → renda mensal passiva via aluguéis\nETFs → diversificação barata e automática\nBDRs → acesso ao mercado internacional\nOpções → proteção ou alavancagem (avançado)\nCripto → altíssimo risco, altíssimo potencial", "emoji": "🎯"},
  {"type": "activity", "question": "Qual tipo de investimento em renda variável é mais indicado para quem quer receber renda mensal passiva?", "options": ["Criptomoedas", "Opções", "FIIs — Fundos Imobiliários", "BDRs"], "correct": 2},
  {"type": "true_false", "statement": "ETFs são indicados para investidores que querem selecionar manualmente cada ação da carteira com alta precisão.", "correct": 0, "explanation": "Falso! ETFs são o oposto disso — são indicados para quem quer diversificação automática sem precisar escolher cada ativo individualmente."},
  {"type": "match_pairs", "pairs": [{"term": "ETF", "definition": "Melhor para diversificação automática e baixo custo"}, {"term": "FII", "definition": "Melhor para renda mensal via aluguéis"}, {"term": "BDR", "definition": "Melhor para exposição ao mercado internacional"}, {"term": "Cripto", "definition": "Maior potencial — e maior risco — da renda variável"}]}
]'),
(gen_random_uuid(), 3, 'Tipos de Investimentos', 8, '3.8 Qual Combina com Você Agora?', 25, false, '[
  {"type": "explanation", "title": "Autoconhecimento antes de tudo 🪞", "body": "Antes de escolher onde investir, você precisa se conhecer como investidor. Quanto risco você aguenta sem perder o sono? Qual é seu objetivo — crescimento, renda ou segurança? Em quanto tempo você precisará do dinheiro? As respostas a essas perguntas determinam qual tipo de renda variável faz sentido pra você agora.", "emoji": "💡"},
  {"type": "example", "title": "Três Perfis, Três Caminhos 🛤️", "body": "João, 18 anos, estudante, pode esperar 20 anos: ações e ETFs fazem sentido — tempo é seu maior aliado. Maria, 35 anos, quer renda extra sem risco alto: FIIs são a pedida — renda mensal sem tanta oscilação. Pedro, 25 anos, curioso por tecnologia, aceita risco: uma fatia pequena em BDRs de techs americanas pode funcionar. Não há resposta certa — há resposta certa pra cada pessoa.", "highlight": "Iniciante: ETFs e FIIs — simplicidade e diversificação\nQuem quer renda: FIIs — distribuição mensal\nQuem quer crescimento: ações de empresas sólidas\nQuem quer internacional: BDRs ou ETFs globais\nEvitar por enquanto: opções e cripto como posição principal", "emoji": "🎯"},
  {"type": "activity", "question": "Para um investidor iniciante que quer simplicidade e diversificação imediata, qual é a opção mais indicada?", "options": ["Opções de ações para alavancar ganhos", "Criptomoedas pelo alto potencial de retorno", "ETFs pelo baixo custo e diversificação automática", "Day trade de ações para lucros rápidos"], "correct": 2},
  {"type": "true_false", "statement": "Um jovem de 20 anos com horizonte de investimento de 30 anos deve evitar completamente ações, pois são arriscadas demais.", "correct": 0, "explanation": "Falso! O longo horizonte de tempo é exatamente o que torna ações adequadas para jovens. O tempo reduz o risco, pois permite atravessar crises e capturar o crescimento de longo prazo das empresas."},
  {"type": "fill_in_the_blank", "sentence": "O conjunto de investimentos de uma pessoa, distribuídos entre diferentes ativos, é chamado de ____.", "answer": "carteira", "hint": "Também chamada de portfólio — onde você guarda seus investimentos. 👜", "explanation": "Isso! Carteira (ou portfólio) é o conjunto total de investimentos de uma pessoa — ações, FIIs, ETFs e tudo mais."},
  {"type": "match_pairs", "pairs": [{"term": "Perfil conservador", "definition": "Prefere segurança e aceita retornos menores"}, {"term": "Perfil moderado", "definition": "Equilibra risco e retorno na carteira"}, {"term": "Perfil arrojado", "definition": "Aceita alta volatilidade em busca de maior retorno"}, {"term": "Horizonte de tempo", "definition": "Prazo em que o investidor pode manter o dinheiro investido"}]}
]'),
(gen_random_uuid(), 3, 'Tipos de Investimentos', 9, '3.9 Quiz do Módulo 🎯', 25, true, '[
  {"type": "activity", "question": "Qual tipo de investimento distribui aluguéis mensalmente aos cotistas?", "options": ["Ações ON", "ETFs", "FIIs", "BDRs"], "correct": 2},
  {"type": "activity", "question": "O que é um ETF?", "options": ["Um fundo que investe apenas em imóveis", "Um fundo negociado em bolsa que replica um índice", "Um certificado de ação estrangeira", "Um contrato de compra e venda futura"], "correct": 1},
  {"type": "activity", "question": "Qual sufixo identifica um BDR no ticker brasileiro?", "options": ["3", "11", "34", "4"], "correct": 2},
  {"type": "activity", "question": "Uma opção de venda (Put) dá ao comprador o direito de:", "options": ["Comprar o ativo pelo preço de mercado", "Vender o ativo por um preço combinado até uma data", "Receber dividendos da empresa emissora", "Votar nas assembleias da empresa"], "correct": 1},
  {"type": "activity", "question": "Qual é a principal diferença das criptomoedas em relação às ações?", "options": ["Criptomoedas têm regulação mais rígida", "Criptomoedas têm volatilidade muito maior e sem lastro em empresas", "Criptomoedas pagam dividendos mensais", "Criptomoedas são mais seguras que ações"], "correct": 1},
  {"type": "activity", "question": "O IVVB11 é um ETF que replica qual índice?", "options": ["Ibovespa", "IFIX", "S&P 500", "NASDAQ"], "correct": 2},
  {"type": "activity", "question": "Para um investidor que quer exposição ao mercado americano sem abrir conta no exterior, o mais indicado é:", "options": ["FIIs", "BDRs ou ETFs globais", "Opções", "Criptomoedas"], "correct": 1},
  {"type": "activity", "question": "O que representa o prêmio em uma operação com opções?", "options": ["O lucro garantido ao final do contrato", "O dividendo pago pela empresa ao titular", "O valor pago pelo comprador pelo contrato da opção", "A taxa cobrada pela corretora na operação"], "correct": 2},
  {"type": "activity", "question": "Qual característica faz dos FIIs uma opção atrativa para geração de renda passiva?", "options": ["Alto potencial de valorização diária", "Distribuição mensal de aluguéis dos imóveis do fundo", "Isenção total de imposto de renda", "Garantia de retorno mínimo pelo governo"], "correct": 1},
  {"type": "activity", "question": "Qual tipo de renda variável tem o maior nível de risco e volatilidade?", "options": ["ETFs de índice", "FIIs de tijolo", "Ações blue chips", "Criptomoedas"], "correct": 3}
]')
ON CONFLICT DO NOTHING;

-- Verificar inserção
SELECT 'Módulo 3 inserido com sucesso!' as resultado;